version: '3'
services:
  clickhouse-db:
    image: loghole/clickhouse-db:0.5.1
    volumes:
      - './data/clickhouse:/var/lib/clickhouse'

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"

  collector:
    image: loghole/collector:0.6.0
    volumes:
      - './configs:/configs'
      - './certs:/certs'
    ports:
      - 50000:8080
    depends_on:
      - clickhouse-db
      - jaeger

  dashboard:
    image: loghole/dashboard:0.6.0
    volumes:
      - './configs:/configs'
      - './certs:/certs'
    ports:
      - 8080:8080
    depends_on:
      - clickhouse-db
      - jaeger
